### ISSUE TITLE
Module 'asyncio' has no 'run' member in Python 3.6 

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-microphone-cli-hermes#7]
https://github.com/rhasspy/rhasspy-microphone-cli-hermes/runs/587062662?check_suite_focus=true

Same issue as https://github.com/rhasspy/rhasspy-dialogue-hermes/issues/2

**Comment by synesthesiam** [comment]
Closed so discussion happens over on linked issue
