### ISSUE TITLE
How am I supposed to run this?

### ISSUE THREAD

**Issue by ntrp** [rhasspy/rhasspy-microphone-cli-hermes#8]
Sorry for the ignorance but although the mandatory parameters are `--record-command, --sample-rate, --sample-width, --channels` it is absolutely not clear what should I put in there..

Could you provide a slightly more detailed documentation or if I missed it point me to it?

**Comment by synesthesiam** [comment]
See here for an example with `arecord`: https://github.com/rhasspy/rhasspy-supervisor/blob/5745d4fc15df9f031679240f06dc9c5001cc4421/rhasspysupervisor/__init__.py#L354

**Comment by ntrp** [comment]
I found it in the meantime but thanks!
